[package]
name = "swrite"
version = "0.1.0"
description = "Infallible alternatives to write! and writeln! for Strings"
documentation = "https://docs.rs/write/"
homepage = "https://github.com/rusticstuff/swrite"
repository = "https://github.com/rusticstuff/swrite"
readme = "README.md"
keywords = [ "string", "write", "writeln", "formatting", "macro"]
categories = [ "text-processing", "value-formatting" ]
license = "MIT OR Apache-2.0"
exclude = [
    "/.gitignore",
    "/.github",
    "/.vscode",
]

[features]
# make `swrite!` and `swriteln!` work for `std::ffi::OsString` as well
# requires Rust 1.64.0 or later
osstring = []

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
