name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "17 3 * * 1"

jobs:
  test:
    strategy:
      matrix:
        toolchain: ["1.64.0", stable, beta, nightly]
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --all-features
  msrv:
    name: cargo test (1.30.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.30.0
      - run: cargo test
  clippy-fmt-doc:
    name: cargo fmt / cargo clippy / cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: Running cargo fmt, cargo clippy and cargo doc
        run: |
          cargo fmt -- --check
          cargo clippy --all-features -- -D warnings
          cargo doc --all-features

